# Generated by Django 5.2.2 on 2025-06-08 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do produto', max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, help_text='Descrição do produto', null=True)),
                ('quantidade', models.IntegerField(default=0, help_text='Quantidade atual em estoque')),
            ],
        ),
        migrations.CreateModel(
            name='Movimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(help_text='Quantidade movimentada')),
                ('data_hora', models.DateField(help_text='Data do movimento (sem a hora)')),
                ('data_ultima_movimentacao', models.DateField(blank=True, help_text='Data da última entrada ou saída do produto', null=True)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], help_text='Tipo de movimento (Entrada/Saída)', max_length=1)),
                ('produto', models.ForeignKey(help_text='Produto movimentado', on_delete=django.db.models.deletion.CASCADE, to='estoque.produto')),
            ],
        ),
    ]
