# Generated by Django 5.2.2 on 2025-06-08 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_remove_produto_descricao_alter_produto_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimento',
            name='data_hora',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='data_ultima_movimentacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto'),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='movimento',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1),
        ),
    ]
